version: '3.5'
services:
  grafana:
    restart: always
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    deploy:
     replicas: 1
     restart_policy:
      condition: on-failure
     resources:
        limits:
          cpus: '0.1'
          memory: "256M"
    #volumes:
    #  - ./grafana/:/etc/grafana/provisioning/    
    #  - /media/sdb1/grafana:/var/lib/grafana      
    environment:     
     - SERVICE_NAME=grafana
     - SERVICE_TAGS=apm